### ISSUE TITLE
[kudu1] dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-jxlOHAPnbi: Connection refused

### ISSUE THREAD

**Issue by 130s** [130s/compenv_ubuntu#55]
Using https://github.com/130s/compenv_ubuntu/pull/48/commits/68205054607411f0c3a9e9b5f8bea17fb169b960, GUI often fail and exit.

```
$ echo $DISPLAY
:0

$ meld . &
[1] 19252
(meld:19252): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-OUvnQFsjtD: Connection refused

(meld:19252): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-GTarGXZSEl: Connection refused
Traceback (most recent call last):
  File "/usr/bin/meld", line 178, in <module>
    main()
  File "/usr/bin/meld", line 164, in main
    already_running, dbus_app = meld.dbus_service.setup(app)
  File "/usr/lib/meld/meld/dbus_service.py", line 56, in setup
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-jxlOHAPnbi: Connection refused

[1]+  Exit 1                  meld .
$ sudo service messagebus restart
messagebus: unrecognized service
$ pwd
/home/n130s/link/ROS/indigo_trusty/cws_planning/tmp/davetcoleman/moveit
$ unset $DISPlAY
$ export DISPlAY=localhost:0.0
$ meld . &
[1] 19297
$
(meld:19297): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-HO2Gi4pxFd: Connection refused

(meld:19297): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-Q3kzqdScvy: Connection refused
Traceback (most recent call last):
  File "/usr/bin/meld", line 178, in <module>
    main()
  File "/usr/bin/meld", line 164, in main
    already_running, dbus_app = meld.dbus_service.setup(app)
  File "/usr/lib/meld/meld/dbus_service.py", line 56, in setup
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-8SCKfjiCbQ: Connection refused

[1]+  Exit 1                  meld .
```

But with emacs, I see the similar/same error but it runs.

**Comment by 130s** [comment]
Out of `tmux` context this doesn't happen.

**Comment by 130s** [comment]
A little more info.

- While set `DISPLAY` as `:0`, on `tmux` fails but on no-tmux it works.

- This doesn't occur with `evince`.

- With `nautilus` I see errors but window still functions.
 ```
$ nautilus
Unable to initialize DBus connection: Could not connect: Connection refused
(nautilus:4056): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_export: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Initializing nautilus-dropbox 2015.10.28

(nautilus:4056): libunity-CRITICAL **: unity-launcher.vala:154: Unable to connect to session bus: Could not connect: Connection refused

(nautilus:4056): libunity-CRITICAL **: unity-launcher.vala:154: Unable to connect to session bus: Could not connect: Connection refused

(nautilus:4056): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Could not connect: Connection refused

(nautilus:4056): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Could not connect: Connection refused
Nautilus-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.
```
